# My First Jupyter Notebook

In QSO370 we'll be using Jupyter Notebooks which embed both text and python code, to construct reproducible analyses. This is our first Jupyter Notebook for the course. Double-click into this text to see the cell that produces the text on the left and the formatted text on the right. Then follow along to see how formatting in Jupyter works.

We can type text freely and Jupyter will automatically format it for us in a presentable manner. 
Notice that we need to "skip a line" if we want to create a new paragraph.

We can also use some simple markdown code to format the text portion of our notebooks. You can surround text by a single asterisk (\*) to make it appear in *italics* or with two asterisks to make it appear in **bold** -- you'll notice that I needed to use a backslash prior to the asterisk symbol in order for it to actually appear in the text -- this is because the asterisk is a *special character* which needs to be *escaped* with the backslash if you want it to be printed into the notebook. You've already seen the use of the hastag (\#) to create a *level-one* header, or *title*). You can create level-two, -three, or higher-order headers just by using additional hastags. For example, preceed a line of text with two hashtags to create a level-two heading (section).

You may also want to create lists in your notebooks. If order is not important for my lists, we can create an unordred list using the + symbol to begin each list item line.
+ This is an item in my list
+ This is another item in my list

If order is important for the items in my list, we can number the items.
1. This is the first item in my list.
2. This is the second item in my list.
  + Hit tab and use a + sign to generate a sub-item in the list.

We can render the text cell into the notebook by using the key combination `Shift+Enter`. Notice how I formatted that? Using these single back-tics is a really convenient way to format unexecuted code or computer instructions within a text section.

In [ ]:
#Notice that when you run a cell with the Shift+Enter combination, a new cell is 
#created automatically if there is no existing cell that follows. This new cell 
#is a "code" cell by default -- you can see that everything here is formatting 
#quite differently. The hashtags at the beginning of these lines is a comment 
#symbol, telling our notebook to ignore the text that follows -- its just 
#explanations for humans to read, nothing that the computer must execute. You
#can execute this cell with the Shift+Enter combination, just like you did the 
#text cell above.

In [ ]:
#The code cell above was really silly -- there's no code in it -- just a comment. 
#It should really be reformatted as a text cell, with all those hashtags removed. 
#Code cells should pass instructions for the computer to follow and execute. For 
#example, we could ask the computer to find the value of 2 + 8
2 + 8

10

In [ ]:
4 + 10 - 18 #Here is another arithmetic operation with a comment on the same line.

-4

In [ ]:
#If we run several individual computations, note that only the result of the 
#final computation is printed.
2 + 8
4 + 10 - 8
8*5 - 17

23

In [ ]:
#To print multiple outputs from a single cell, you should use the print() 
#function as a wrapper.
print(2 + 8)
print(4 + 10 - 8)
print(8*5 - 17)

10
6
23

In [ ]:
#Notice that Python is really picky. Let's generate an error (the first of many 
#we'll encounter in our course). Try executing 2(6 - 20) -- I've already typed
#it for you at the bottom of the cell -- execute the cell with Shift+Enter. Do 
#this now, before reading further.

#Notice an error is thrown, stating that an 'int' object is not callable. At this 
#point that error likely means nothing to you, however, parentheses in python are 
#very special objects -- if we don't precede the opening parentheses with an 
#asterisk then python interprets the object on the left of the opening 
#parentheses as a function name, and the items inside of the parentheses as 
#arguments. Essentially we've asked python to apply the function named '2' to 
#the argument '6 - 20'. The object '2' is an integer (int), not a function -- 
#that is, we can't call '2' on aguments. This will make more sense as we 
#encounter more errors in our course -- and there will be plenty! For now, fix 
#the error by running 2*(6 - 20) instead of 2(6 - 20).

2(6 - 20)

TypeError: ignored

Okay, that's enough for now. You'll get some practice formatting a Jupyter Notebook on Homework 0. Try that assignment now.